package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"time"

	"github.com/opendesk-remote/opendesk-remote/builder/internal/buildspec"
	"github.com/opendesk-remote/opendesk-remote/builder/internal/injector"
	"github.com/opendesk-remote/opendesk-remote/builder/internal/platforms"
	"github.com/opendesk-remote/opendesk-remote/builder/internal/runners"
)

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	var err error
	switch os.Args[1] {
	case "validate":
		err = validate(os.Args[2:])
	case "inject":
		err = inject(os.Args[2:])
	case "doctor":
		err = doctor(os.Args[2:])
	case "run":
		err = run(os.Args[2:])
	default:
		usage()
		os.Exit(2)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "error:", err)
		os.Exit(1)
	}
}

func validate(args []string) error {
	flags := flag.NewFlagSet("validate", flag.ContinueOnError)
	specPath := flags.String("spec", "", "BuildSpec JSON path")
	if err := flags.Parse(args); err != nil {
		return err
	}
	spec, err := loadSpec(*specPath)
	if err != nil {
		return err
	}
	fmt.Println("valid BuildSpec:", spec.Summary())
	return nil
}

func doctor(args []string) error {
	flags := flag.NewFlagSet("doctor", flag.ContinueOnError)
	platform := flags.String("platform", platforms.WindowsX64, "platform to inspect")
	sourceDir := flags.String("source", "", "patched RustDesk source directory")
	buildCommand := flags.String("build-command", "", "platform build command")
	artifactGlob := flags.String("artifact-glob", "", "glob for artifacts generated by the build command")
	dryRun := flags.Bool("dry-run", false, "inspect dry-run requirements only")
	timeout := flags.Duration("timeout", 30*time.Second, "doctor timeout")
	if err := flags.Parse(args); err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()
	var report runners.PreflightReport
	switch *platform {
	case platforms.WindowsX64:
		report = runners.CheckWindows(ctx, runners.WindowsConfig{
			SourceDir:    *sourceDir,
			BuildCommand: *buildCommand,
			ArtifactGlob: *artifactGlob,
			DryRun:       *dryRun,
		})
	default:
		return fmt.Errorf("doctor not implemented for platform: %s", *platform)
	}
	raw, err := json.MarshalIndent(report, "", "  ")
	if err != nil {
		return err
	}
	fmt.Println(string(raw))
	if !report.Ready {
		return fmt.Errorf("%s build environment is not ready", *platform)
	}
	return nil
}

func run(args []string) error {
	flags := flag.NewFlagSet("run", flag.ContinueOnError)
	specPath := flags.String("spec", "", "BuildSpec JSON path")
	platform := flags.String("platform", platforms.WindowsX64, "platform to run")
	sourceDir := flags.String("source", "", "patched RustDesk source directory")
	injectionDir := flags.String("injection", "", "injection working directory")
	artifactDir := flags.String("artifacts", "", "artifact output directory")
	buildCommand := flags.String("build-command", "", "platform build command")
	artifactGlob := flags.String("artifact-glob", "", "glob for artifacts generated by the build command")
	dryRun := flags.Bool("dry-run", false, "stage files without running the build command")
	timeout := flags.Duration("timeout", 2*time.Hour, "build timeout")
	if err := flags.Parse(args); err != nil {
		return err
	}
	spec, err := loadSpec(*specPath)
	if err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(context.Background(), *timeout)
	defer cancel()
	var result runners.Result
	switch *platform {
	case platforms.WindowsX64:
		result, err = runners.RunWindows(ctx, spec, runners.WindowsConfig{
			SourceDir:    *sourceDir,
			InjectionDir: *injectionDir,
			ArtifactDir:  *artifactDir,
			BuildCommand: *buildCommand,
			ArtifactGlob: *artifactGlob,
			DryRun:       *dryRun,
		})
	default:
		return fmt.Errorf("runner not implemented for platform: %s", *platform)
	}
	raw, marshalErr := json.MarshalIndent(result, "", "  ")
	if marshalErr != nil {
		return marshalErr
	}
	fmt.Println(string(raw))
	return err
}

func inject(args []string) error {
	flags := flag.NewFlagSet("inject", flag.ContinueOnError)
	specPath := flags.String("spec", "", "BuildSpec JSON path")
	outDir := flags.String("out", "", "output directory")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if *outDir == "" {
		return fmt.Errorf("--out is required")
	}
	spec, err := loadSpec(*specPath)
	if err != nil {
		return err
	}
	manifest, err := injector.Generate(spec, *outDir)
	if err != nil {
		return err
	}
	raw, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return err
	}
	fmt.Println(string(raw))
	return nil
}

func loadSpec(path string) (buildspec.Spec, error) {
	if path == "" {
		return buildspec.Spec{}, fmt.Errorf("--spec is required")
	}
	return buildspec.Load(path)
}

func usage() {
	fmt.Println("opendesk-builder")
	fmt.Println()
	fmt.Println("Commands:")
	fmt.Println("  validate --spec buildspec.json")
	fmt.Println("  inject   --spec buildspec.json --out .run/client-injection")
	fmt.Println("  doctor   --platform windows_x64 --source .upstream/rustdesk-client")
	fmt.Println("  run      --platform windows_x64 --spec buildspec.json --source .upstream/rustdesk-client --injection .run/client-injection --artifacts .run/artifacts --dry-run")
}
