package injector

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"

	"github.com/opendesk-remote/opendesk-remote/builder/internal/buildspec"
)

type Manifest struct {
	App       string          `json:"app"`
	BundleID  string          `json:"bundle_id"`
	Platforms []string        `json:"platforms"`
	Files     []GeneratedFile `json:"files"`
}

type GeneratedFile struct {
	Path   string `json:"path"`
	SHA256 string `json:"sha256"`
	Bytes  int    `json:"bytes"`
}

func Generate(spec buildspec.Spec, outDir string) (Manifest, error) {
	if err := spec.Validate(); err != nil {
		return Manifest{}, err
	}
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return Manifest{}, err
	}
	manifest := Manifest{
		App:       spec.App.Name,
		BundleID:  spec.App.BundleID,
		Platforms: spec.Platforms.Ordered(),
	}
	files := []struct {
		path string
		data []byte
	}{
		{"opendesk/buildspec.normalized.json", mustNormalized(spec)},
		{"opendesk/branding.json", mustJSON(spec.Branding)},
		{"opendesk/policy.json", mustJSON(spec.Policy)},
		{"rust/src/opendesk_generated.rs", rustConfig(spec)},
	}
	for _, file := range files {
		generated, err := writeFile(outDir, file.path, file.data)
		if err != nil {
			return Manifest{}, err
		}
		manifest.Files = append(manifest.Files, generated)
	}
	manifestData := mustJSON(manifest)
	if _, err := writeFile(outDir, "opendesk/manifest.json", manifestData); err != nil {
		return Manifest{}, err
	}
	return manifest, nil
}

func writeFile(root, relativePath string, data []byte) (GeneratedFile, error) {
	fullPath := filepath.Join(root, filepath.FromSlash(relativePath))
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o755); err != nil {
		return GeneratedFile{}, err
	}
	if err := os.WriteFile(fullPath, data, 0o644); err != nil {
		return GeneratedFile{}, err
	}
	sum := sha256.Sum256(data)
	return GeneratedFile{
		Path:   relativePath,
		SHA256: hex.EncodeToString(sum[:]),
		Bytes:  len(data),
	}, nil
}

func rustConfig(spec buildspec.Spec) []byte {
	defaultSettings := mustCompactJSON(spec.Policy.DefaultSettings)
	overrideSettings := mustCompactJSON(spec.Policy.OverrideSettings)
	var buf bytes.Buffer
	buf.WriteString("// Code generated by opendesk-builder. Do not edit.\n")
	buf.WriteString("pub const OPENDESK_APP_NAME: &str = " + strconv.Quote(spec.App.Name) + ";\n")
	buf.WriteString("pub const OPENDESK_VENDOR: &str = " + strconv.Quote(spec.App.Vendor) + ";\n")
	buf.WriteString("pub const OPENDESK_BUNDLE_ID: &str = " + strconv.Quote(spec.App.BundleID) + ";\n")
	buf.WriteString("pub const OPENDESK_WINDOWS_PRODUCT_NAME: &str = " + strconv.Quote(spec.App.WindowsProductName) + ";\n")
	buf.WriteString("pub const OPENDESK_ID_SERVER: &str = " + strconv.Quote(spec.Server.IDServer) + ";\n")
	buf.WriteString("pub const OPENDESK_RELAY_SERVER: &str = " + strconv.Quote(spec.Server.RelayServer) + ";\n")
	buf.WriteString("pub const OPENDESK_RELAY_NAME: &str = " + strconv.Quote(spec.Server.RelayName) + ";\n")
	buf.WriteString("pub const OPENDESK_API_SERVER: &str = " + strconv.Quote(spec.Server.APIServer) + ";\n")
	buf.WriteString("pub const OPENDESK_SERVER_KEY: &str = " + strconv.Quote(spec.Server.Key) + ";\n")
	buf.WriteString("pub const OPENDESK_WEBSOCKET: bool = " + strconv.FormatBool(spec.Server.WebSocket) + ";\n")
	buf.WriteString("pub const OPENDESK_RELAY_GRANT_REQUIRED: bool = " + strconv.FormatBool(spec.RelayGrantRequired()) + ";\n")
	buf.WriteString("pub const OPENDESK_POLICY_PROFILE: &str = " + strconv.Quote(spec.Policy.Profile) + ";\n")
	buf.WriteString("pub const OPENDESK_DEFAULT_SETTINGS_JSON: &str = " + strconv.Quote(string(defaultSettings)) + ";\n")
	buf.WriteString("pub const OPENDESK_OVERRIDE_SETTINGS_JSON: &str = " + strconv.Quote(string(overrideSettings)) + ";\n")
	return buf.Bytes()
}

func mustNormalized(spec buildspec.Spec) []byte {
	data, err := spec.NormalizedJSON()
	if err != nil {
		panic(err)
	}
	return append(data, '\n')
}

func mustJSON(value any) []byte {
	data, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		panic(err)
	}
	return append(data, '\n')
}

func mustCompactJSON(value any) []byte {
	data, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return data
}
